name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-front:
    runs-on: ubuntu-latest
    container: node:16-alpine
    defaults:
      run:
        working-directory: app
    steps:
      - name: Install git and rsync 📚
        run: |
          apk update && apk add git rsync
        working-directory: ../
      - name: Configure git to trust the workspace despite the different owner
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory /__w/bymagg.github.io/github-pages-deploy-action-temp-deployment-folder
        working-directory: ../
      - uses: actions/checkout@v2
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install
      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href https://bymagg.github.io/HighTracks/
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref,'refs/heads/master')
        with:
          branch: gh-pages
          folder: app/www
          clean: true
  build-back:
    runs-on: ubuntu-latest
    container: node:16-alpine
    defaults:
        run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test-jenkins 