name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      CLIENT_ID: {{ secrets.CLIENT_ID }}
      CLIENT_SECRET: {{ secrets.CLIENT_SECRET }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'un-valor-para-que-no-de-error'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
           ssh ubuntu@${{ secrets.SSH_HOST }} "if [ ! -d 'HighTracks' ]; then \
               git clone https://github.com/byMagg/HighTracks.git; \
             else \
               cd HighTracks/api && git stash && git fetch --all && git reset --hard origin/master && git pull origin master; \
             fi"
           ssh ubuntu@${{ secrets.SSH_HOST }} "if pgrep node; then forever stopall; fi"
           ssh ubuntu@${{ secrets.SSH_HOST }} "cd HighTracks/api && npm install"
           ssh ubuntu@${{ secrets.SSH_HOST }} "cd HighTracks/api && forever start src/main.js"