name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-push-to-gcr-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }}'
      - name: Building and pushing the image
        working-directory: api
        run: |
          echo ${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }} | docker login -u _json_key --password-stdin https://gcr.io
          docker build -t gcr.io/${{ vars.GCLOUD_PROJECT_ID }}/hightracks-api:${{ github.sha }} .
          docker push gcr.io/${{ vars.GCLOUD_PROJECT_ID }}/hightracks-api:${{ github.sha }}